package com.ilozanof.kotlin.learning.basics

/**
 * The class below has been automatically generated by the JAva-To-Kotlin
 * converter, including javadoc comments.
 *
 * NOTE: The classname has been changed to "PersonKT", so there are no conflicts
 * with the original "Person" Java class.
 */

/**
 * Small class to store Person information.
 */
class PersonKT(val name: String)
